// 论文数据 - 手动维护
const PAPERS = [
  // === 我的论文（待发表/在投） ===
  {
    id: 'cow-nav',
    title: 'CoW-Nav: Confidence-Weighted Navigation with Formally Structured Chain of Thought',
    authors: 'Jingwei013',
    venue: 'ICRA 2027 / RAL',
    year: 2027,
    type: 'mine',
    status: 'writing',
    arxiv: '',
    github: '',
    abstract: '提出FSCoT（形式化结构化思维链）+ 信心头的双头架构，解决VLN任务中的"该停不停"问题。核心创新：稀疏思维链推理 + 置信度校准停止决策。',
    tags: ['CoW-Nav', 'stop-decision', 'VLN', 'FSCoT'],
    progress: 20
  },
  {
    id: 'embodied-slam',
    title: 'EmbodiedSLAM: Tri-Modal Fusion for Embodied Navigation',
    authors: 'Jingwei013',
    venue: 'ICRA 2027 / IROS 2026',
    year: 2026,
    type: 'mine',
    status: 'planning',
    arxiv: '',
    github: '',
    abstract: '三模态融合：视觉里程计 + 语言先验 + 语义地图，构建具身智能的统一导航框架。',
    tags: ['EmbodiedSLAM', 'SLAM', 'tri-modal'],
    progress: 5
  },

  // === 参考论文：停止决策 ===
  {
    id: 'haltnav-pro',
    title: 'HaltNav-Pro: Adaptive Threshold Stopping for Vision-Language Navigation',
    authors: 'Various',
    venue: 'ICRA 2025',
    year: 2025,
    type: 'ref',
    venueType: 'conference',
    arxiv: '',
    abstract: '自适应阈值方法，R2R StoP +3.2%，为停止决策提供baseline对比。',
    tags: ['stop-decision', 'VLN', 'threshold'],
    github: ''
  },
  {
    id: 'evolvnav-2',
    title: 'EvolveNav-2: Online Chain-of-Thought Self-Improvement for VLN',
    authors: 'Various',
    venue: 'ICRA 2025',
    year: 2025,
    type: 'ref',
    venueType: 'conference',
    arxiv: '',
    abstract: '在线CoT自改进，长距离SR +5.1%，展示CoT推理在VLN中的潜力。',
    tags: ['CoT', 'VLN', 'self-improvement'],
    github: ''
  },
  {
    id: 'vlr1',
    title: 'VLN-R1: Reinforcement Learning with Chain-of-Thought for VLN',
    authors: 'Various',
    venue: 'arXiv 2026',
    year: 2026,
    type: 'ref',
    venueType: 'arxiv',
    arxiv: '',
    abstract: 'RLHF + CoT，探索性工作，验证CoT在VLN中的有效性。',
    tags: ['VLN', 'RLHF', 'CoT'],
    github: ''
  },
  {
    id: 'live-ln',
    title: 'LiveLN: LiDAR-Visual-Enhanced Navigation in Unseen Environments',
    authors: 'Various',
    venue: 'ICRA 2026',
    year: 2026,
    type: 'ref',
    venueType: 'conference',
    arxiv: '',
    abstract: 'LiDAR增强的VLN方法，提供跨模态定位参考。',
    tags: ['VLN', 'LiDAR', 'cross-modal'],
    github: ''
  },
  {
    id: 'navdp',
    title: 'NavDP: Depth-Progressive Planning for VLN',
    authors: 'Various',
    venue: 'ICRA 2026',
    year: 2026,
    type: 'ref',
    venueType: 'conference',
    arxiv: '',
    abstract: '深度递进规划，提供分层决策参考。',
    tags: ['VLN', 'planning', 'hierarchical'],
    github: ''
  },
  {
    id: 'dreamnav',
    title: 'DreamNav: World Model Predictive Planning for VLN',
    authors: 'Various',
    venue: 'ICRA 2026',
    year: 2026,
    type: 'ref',
    venueType: 'conference',
    arxiv: '',
    abstract: '世界模型预测规划，与CoW-Nav方向高度相关。',
    tags: ['world-model', 'VLN', 'predictive'],
    github: ''
  },
  {
    id: 'fantasyvla',
    title: 'FantasyVLA: Fast Chain-of-Thought for Vision-Language-Action',
    authors: 'Various',
    venue: 'CVPR 2026',
    year: 2026,
    type: 'ref',
    venueType: 'conference',
    arxiv: '',
    abstract: 'FantasyVLA快速CoT方法，对比FSCoT设计的重要参考。',
    tags: ['VLA', 'CoT', 'fast-inference'],
    github: ''
  },
  {
    id: 'acot-vla',
    title: 'ACoT-VLA: Action Chain-of-Thought for Vision-Language-Action Models',
    authors: 'Various',
    venue: 'CVPR 2026',
    year: 2026,
    type: 'ref',
    venueType: 'conference',
    arxiv: '',
    abstract: '动作链思维，为CoW-Nav的动作停止决策提供参考。',
    tags: ['VLA', 'action-CoT', 'CVPR2026'],
    github: ''
  },
  {
    id: 'vl-calibration',
    title: 'VL-Calibration: Vision-Language Confidence Calibration for VLN',
    authors: 'Various',
    venue: 'ICLR 2026',
    year: 2026,
    type: 'ref',
    venueType: 'conference',
    arxiv: '',
    abstract: 'VLM置信度校准，直接关联CoW-Nav信心头设计。',
    tags: ['calibration', 'confidence', 'VLM'],
    github: ''
  },
  {
    id: 'rule-vln',
    title: 'Rule-VLN: Social Compliance for VLN Navigation',
    authors: 'Various',
    venue: 'arXiv 2026',
    year: 2026,
    type: 'ref',
    venueType: 'arxiv',
    arxiv: '',
    abstract: '社会合规VLN，CVR指标与CoW-Nav双头扩展高度相关。',
    tags: ['VLN', 'social-compliance', 'rule-based'],
    github: ''
  },
  {
    id: 'vla-nav',
    title: 'VLA-Nav: End-to-End VLA Navigation without Fine-tuning',
    authors: 'Various',
    venue: 'arXiv 2026',
    year: 2026,
    type: 'ref',
    venueType: 'arxiv',
    arxiv: '',
    abstract: '无需微调的VLA导航，零样本泛化能力验证。',
    tags: ['VLA', 'zero-shot', 'navigation'],
    github: ''
  },
  {
    id: 'lazyvlp',
    title: 'LazyVLP: Lazy Vision-Language Planning for Long-Horizon VLN',
    authors: 'Various',
    venue: 'ICRA 2026',
    year: 2026,
    type: 'ref',
    venueType: 'conference',
    arxiv: '',
    abstract: '长距离VLN规划，lazy planning策略与FSCoT路由设计相关。',
    tags: ['VLN', 'long-horizon', 'planning'],
    github: ''
  },
  {
    id: 'safenav',
    title: 'SafeNav: Risk-Aware VLN with Safety Constraints',
    authors: 'Various',
    venue: 'IROS 2026',
    year: 2026,
    type: 'ref',
    venueType: 'conference',
    arxiv: '',
    abstract: '安全约束VLN，为停止决策提供安全性参考。',
    tags: ['VLN', 'safety', 'risk-aware'],
    github: ''
  },
  {
    id: 'univ3r',
    title: 'Uni3R: Unified 3D Reasoning for Embodied AI',
    authors: 'Various',
    venue: 'CVPR 2026',
    year: 2026,
    type: 'ref',
    venueType: 'conference',
    arxiv: '',
    abstract: '统一3D推理，感知路径与EmbodiedSLAM直接相关。',
    tags: ['3D-reasoning', 'CVPR2026', 'perception'],
    github: ''
  },
  {
    id: 'safevla',
    title: 'SafeVLA: Safe Vision-Language-Action Models',
    authors: 'Various',
    venue: 'ICRA 2026',
    year: 2026,
    type: 'ref',
    venueType: 'conference',
    arxiv: '',
    abstract: '安全VLA模型，WorldArena评测基准。',
    tags: ['VLA', 'safety', 'benchmark'],
    github: ''
  },
  {
    id: 'navspace',
    title: 'NavSpace: Spatial Intelligence Benchmark for VLN',
    authors: 'Various',
    venue: 'arXiv 2026',
    year: 2026,
    type: 'ref',
    venueType: 'arxiv',
    arxiv: '',
    abstract: '空间智能评测基准，可扩展FSCoT为四段式推理。',
    tags: ['benchmark', 'spatial', 'VLN'],
    github: ''
  },
  {
    id: 'starvla',
    title: 'StarVLA: Spatial-Temporal Action Reasoning for VLA',
    authors: 'Various',
    venue: 'HKUST',
    year: 2025,
    type: 'ref',
    venueType: 'github',
    arxiv: '',
    abstract: '开源VLA项目，Backbone-Action Head解耦架构为CoW-Nav提供模块化设计参考。',
    tags: ['VLA', 'open-source', 'modular'],
    github: 'https://github.com/StarVLA'
  },
  {
    id: 'pi0',
    title: 'π0: Physical Intelligence Generalist Robot Model',
    authors: 'Physical Intelligence',
    venue: '2024',
    year: 2024,
    type: 'ref',
    venueType: 'company',
    arxiv: '',
    abstract: '24亿美元估值验证VLA基础模型商业价值。',
    tags: ['VLA', 'robotics', 'generalist']
  },

  // === 参考论文：早期基础 ===
  {
    id: 'seq2seq-nav',
    title: 'Speaker-Follower Models for VLN',
    authors: 'Fried et al.',
    venue: 'AAAI 2018 / NeurIPS 2018',
    year: 2018,
    type: 'ref',
    venueType: 'conference',
    arxiv: '',
    abstract: '经典VLN baseline，seq2seq attention机制。',
    tags: ['VLN', 'baseline', 'classic'],
    github: ''
  },
  {
    id: 'prevalent',
    title: 'Prevalent: Learning by Instruction for VLN',
    authors: 'Various',
    venue: 'AAAI 2020',
    year: 2020,
    type: 'ref',
    venueType: 'conference',
    arxiv: '',
    abstract: 'R2R数据集上的经典方法。',
    tags: ['VLN', 'R2R', 'baseline'],
    github: ''
  },
  {
    id: 'sim2real-vln',
    title: 'Sim2Real Gap in VLN: Analysis and Mitigation',
    authors: 'Various',
    venue: 'RAL 2022',
    year: 2022,
    type: 'ref',
    venueType: 'journal',
    arxiv: '',
    abstract: 'Sim-to-Real鸿沟分析，为cross-modal drift研究提供基础。',
    tags: ['sim2real', 'cross-modal', 'VLN'],
    github: ''
  }
];